#!/usr/bin/python3
# coding: UTF-8
#  Copyright (c) 2020 Matus Chochlik

import os
import re
import sys
import zlib
import argparse
# ------------------------------------------------------------------------------
class EmberArgumentParser(argparse.ArgumentParser):
    # --------------------------------------------------------------------------
    def _positive_int(self, x):
        try:
            assert(int(x) > 0)
            return int(x)
        except:
            self.error("`%s' is not a positive integer value" % str(x))

    # --------------------------------------------------------------------------
    def __init__(self, **kw):
        argparse.ArgumentParser.__init__(self, **kw)

        self.add_argument(
            '-p', '--packed',
            dest='packed',
            default=False,
            action="store_true"
        )

        self.add_argument(
            '-i', '--input',
            metavar='INPUT-FILE',
            nargs='?',
            type=os.path.realpath,
            default=[],
            action="append"
        )

        self.add_argument(
            '-o', '--output',
            dest='output_path',
            metavar='OUTPUT-FILE',
            nargs='?',
            type=os.path.realpath,
            default=None
        )

        self.add_argument(
            '-s', '--search',
            dest='search_path',
            metavar='DIRECTORY',
            nargs='?',
            type=os.path.realpath,
            default=[],
            action="append"
        )

        self.add_argument(
            '-t', '--target',
            dest='targets',
            metavar=('TARGET', 'RESOURCE-FILE'),
            nargs=2,
            default=[],
            action="append"
        )

        self.add_argument(
            '-l', '--max-line-len',
            dest='max_line_len',
            metavar='COLUMNS',
            nargs='?',
            type=self._positive_int,
            default=80
        )

    # --------------------------------------------------------------------------
    def process_parsed_options(self, options):

        if options.output_path is None:
            options.output = sys.stdout
        else:
            if os.path.isdir(options.output_path):
                options.output_path = os.path.join(
                    options.output_path,
                    'resources.cpp'
                )
            options.output = open(options.output_path, "wt")

        options.target_map = {}
        for target_name, resource_path in options.targets:
            options.target_map[target_name] = resource_path

        return options

    # --------------------------------------------------------------------------
    def parse_args(self):
        return self.process_parsed_options(
            argparse.ArgumentParser.parse_args(self)
        )

# ------------------------------------------------------------------------------
def make_argparser():
    return EmberArgumentParser(
        prog="embed_generator",
        description="""
        makes a compilable C/C++ source file containing
        static embed data from input files.
        """
    )
# ------------------------------------------------------------------------------
class PlainResource(object):
    # --------------------------------------------------------------------------
    def __init__(self, path):
        self._path = path
    # --------------------------------------------------------------------------
    def __enter__(self):
        self._fd = open(self._path, "rb")
        return self
    # --------------------------------------------------------------------------
    def __exit__(self, typ, val, traceback):
        self._fd.close()
    # --------------------------------------------------------------------------
    def byte_size(self):
        return os.stat(self._path).st_size
    # --------------------------------------------------------------------------
    def get_byte(self):
        result = self._fd.read(1)
        if result:
            result = ord(result)
        else:
            result = None
        return result

# ------------------------------------------------------------------------------
class PackedResource(object):
    # --------------------------------------------------------------------------
    def __init__(self, path):
        self._path = path
        self._zipped = []
        self._readpos = -1
    # --------------------------------------------------------------------------
    def __enter__(self):
        with open(self._path, "rb") as rfd:
            self._zipped = zlib.compress(rfd.read(), zlib.Z_BEST_COMPRESSION)
        return self
    # --------------------------------------------------------------------------
    def __exit__(self, typ, val, traceback):
        del self._zipped
    # --------------------------------------------------------------------------
    def byte_size(self):
        return len(self._zipped)
    # --------------------------------------------------------------------------
    def get_byte(self):
        result = None
        if self._readpos < 0:
            result = 1
            self._readpos = 0
        elif self._readpos < len(self._zipped):
            result = self._zipped[self._readpos]
            self._readpos += 1
        return result

# ------------------------------------------------------------------------------
def load_resource(options, resource_path):
    if options.packed:
        return PackedResource(resource_path)
    return PlainResource(resource_path)

# ------------------------------------------------------------------------------
def make_res_code(options, ident, path):
    linelen = 0
    first = True
    resource_path = options.target_map.get(path, path)
    if not os.path.isfile(resource_path):
        for search_dir in options.search_path:
            if os.path.isfile(os.path.join(search_dir, path)):
                resource_path = os.path.realpath(os.path.join(search_dir, path))
                break

    options.output.write("    if(res_id == EAGINE_ID(%s)) {\n" % ident)

    with load_resource(options, resource_path) as res:
        if res.byte_size() > 0:
            options.output.write("#if !defined(__clang_analyzer__)\n")
            options.output.write("        static const byte res[] = {\n")
        
            while True:
                byte = res.get_byte()
                if byte is None:
                    break

                temp = ""
                if first:
                    first = False
                    temp += "  "
                else:
                    temp += ", "

                temp += "0x%x" % byte
                
                if linelen > options.max_line_len - 16:
                    linelen = 0
                    temp += "\n"
                else:
                    linelen += len(temp)
                options.output.write(temp)
            options.output.write("\n        };\n")
            options.output.write("        return {view(res), path, %s};\n" % (
                "true" if options.packed else "false"
            ))
            options.output.write("#endif\n")
        else:
            options.output.write("        return {};\n")
    options.output.write("    }\n")
# ------------------------------------------------------------------------------
def make_prologue(options):
    options.output.write("#include <eagine/embed.hpp>\n");
    options.output.write("#include <eagine/maybe_unused.hpp>\n");
    options.output.write("namespace eagine {\n")
    options.output.write(
        "embedded_resource get_embedded_resource(identifier res_id, string_view path) noexcept {\n"
    )
    options.output.write("    EAGINE_MAYBE_UNUSED(res_id);\n")
    options.output.write("    EAGINE_MAYBE_UNUSED(path);\n")
# ------------------------------------------------------------------------------
def make_epilogue(options):
    options.output.write("    return {};\n")
    options.output.write("}\n")
    options.output.write("} // namespace eagine\n")
# ------------------------------------------------------------------------------
def make_resource_file(options):
    embed_re = r'embed\(\s*EAGINE_ID\(([a-zA-Z0-9_]+)\),\s*("([^"]+)"|__FILE__)\s*\)'
    some_output = False
    for path in options.input:
        with open(path, "rt") as ifd:
            source = str()
            for line in ifd.readlines():
                source += line
                embeds = re.findall(embed_re, source)
                if embeds:
                    for ident, res_expr, res_path in embeds:
                        if not some_output:
                            make_prologue(options)
                            some_output = True
                        if res_expr == "__FILE__":
                            make_res_code(options, ident, path)
                        else:
                            make_res_code(options, ident, res_path)
                    source = str()
    if some_output:
        make_epilogue(options)

# ------------------------------------------------------------------------------
def main():
    make_resource_file(make_argparser().parse_args())
    return 0
# ------------------------------------------------------------------------------
if __name__ == "__main__":
    exit(main())
# ------------------------------------------------------------------------------
