#!/bin/bash
# Copyright Matus Chochlik.
# Distributed under the Boost Software License, Version 1.0.
# See accompanying file LICENSE_1_0.txt or copy at
#  http://www.boost.org/LICENSE_1_0.txt

kind=${1}
shift
library=${1}
shift
test_src_dir="$(<SOURCE_DIR)/test/${kind}/${library}"
test_bin_dir="$(dirname ${0})/test/${kind}/${library}"

cd "${test_bin_dir}" &&
for test
do
	if [[ -f "${test_src_dir}/${test}.cpp" ]]
	then
		if make ${library}-${test}-${kind}
		then
			if [[ -x ${library}-${test}-${kind} ]]
			then ./${library}-${test}-${kind}
			fi
		fi
	else echo "Invalid '${library}' '${kind}' test name: '${test}'"
	fi
done
