#!/usr/bin/env python3
#  Copyright Matus Chochlik.
#  Distributed under the Boost Software License, Version 1.0.
#  See accompanying file LICENSE_1_0.txt or copy at
#   http://www.boost.org/LICENSE_1_0.txt
#
import os
import sys
import subprocess

if sys.argv[0].endswith(".oglplus/ssh-bridge"):
    try:
        prefix_src = os.path.join(os.path.dirname(sys.argv[0]), "INSTALL_PREFIX")
        with open(prefix_src, "rt") as f:
            prefix = os.environ.get("OGLPLUS_PREFIX",f.readline().strip())
    except Exception:
        prefix = os.environ.get("OGLPLUS_PREFIX", "/usr")

    try:
        orig_argv = os.environ["SSH_ORIGINAL_COMMAND"].split(' ')
        if orig_argv[0].endswith(".oglplus/ssh-bridge"):
            cmd_args = orig_argv[1:]
        else:
            sys.exit(2)
    except:
        cmd_args = sys.argv[1:]

    cmd_dir = os.path.join(
        os.path.realpath(os.path.expanduser("~")),
        ".oglplus", "ssh-bridge-cmd"
    )
    cmd_env = dict(os.environ)
    cmd_env["OGLPLUS_PREFIX"] = prefix
    cmd = os.path.realpath(os.path.join(cmd_dir, cmd_args[0]))
    cmd_args[0] = cmd
    if os.path.isfile(cmd) and os.access(cmd, os.X_OK):
        sys.exit(subprocess.call(cmd_args, env=cmd_env))
else:
    sys.exit(1)

