#!/bin/bash
#  Copyright Matus Chochlik.
#  Distributed under the Boost Software License, Version 1.0.
#  See accompanying file LICENSE_1_0.txt or copy at
#   http://www.boost.org/LICENSE_1_0.txt
#
variant=${1:-007}
log_args=("--use-null-log" "--min-log-severity" "warning")
cmn_args=("--msg-bus-asio-local-stream" "--msg-bus-router-address" "/tmp/oglp-pong")
#
pids=()
${OGLPLUS_PREFIX}/bin/eagine-message_bus-router \
	"${log_args[@]}" "${cmn_args[@]}" \
	--msg-bus-router-id-base 2000 \
	& pids+=($!)
sleep 1
${OGLPLUS_PREFIX}/bin/eagine-message_bus-bridge \
	"${log_args[@]}" "${cmn_args[@]}" \
	& pids+=($!)
sleep 1
${OGLPLUS_PREFIX}/share/oglplus/examples/eagine-${variant}_pong \
	"${log_args[@]}" "${cmn_args[@]}" \
	& pids+=($!)

for pid in ${pids[@]}
do wait ${pid}
done

