#!/bin/bash
#  Copyright Matus Chochlik.
#  Distributed under the Boost Software License, Version 1.0.
#  See accompanying file LICENSE_1_0.txt or copy at
#   http://www.boost.org/LICENSE_1_0.txt
#
let idx=1
for arg
do printf "%3d|%s|\n" ${idx} "${arg}" && let idx+=1
done
