#!/bin/sh
#  Copyright Matus Chochlik.
#  Distributed under the Boost Software License, Version 1.0.
#  See accompanying file LICENSE_1_0.txt or copy at
#   http://www.boost.org/LICENSE_1_0.txt
#
exec ${OGLPLUS_PREFIX}/bin/eagine-message_bus-bridge \
	--use-syslog \
	--min-log-severity info \
	--config-group service

