eagine::msgbus::remote_host Class Reference
OGLplus (0.59.0) a C++ wrapper for rendering APIs
eagine::msgbus::remote_host Class Reference
Message bus
Class providing information about a remote host of bus nodes.
#include <eagine/message_bus/remote_node.hpp>
Public Member Functions
operator bool () const noexcept
Indicates if this is not-empty and has actual information.
auto id () const noexcept -> valid_if_not_zero< host_id_t >
Returns the unique host id.
auto is_alive () const noexcept -> bool
Indicates if the remote host is reachable/alive.
auto name () const noexcept -> valid_if_not_empty< string_view >
Returns the name of the remote host.
auto cpu_concurrent_threads () const noexcept -> valid_if_positive< span_size_t >
Returns the number of concurrent threads supported at the host.
auto short_average_load () const noexcept -> valid_if_nonnegative< float >
Returns the short average load on the remote host.
auto long_average_load () const noexcept -> valid_if_nonnegative< float >
Returns the long average load on the remote host.
auto total_ram_size () const noexcept -> valid_if_positive< span_size_t >
Returns the total RAM size on the remote host.
auto free_ram_size () const noexcept -> valid_if_positive< span_size_t >
Returns the free RAM size on the remote host.
auto ram_usage () const noexcept -> valid_if_nonnegative< float >
Returns the RAM usage on the remote host (0.0, 1.0).
auto total_swap_size () const noexcept -> valid_if_positive< span_size_t >
Returns the total swap size on the remote host.
auto free_swap_size () const noexcept -> valid_if_nonnegative< span_size_t >
Returns the free swap size on the remote host.
auto swap_usage () const noexcept -> valid_if_nonnegative< float >
Returns the swap usage on the remote host (0.0, 1.0).
Detailed Description
Class providing information about a remote host of bus nodes.
See also
remote_node_tracker
remote_node
remote_instance
node_connection
Member Function Documentation
free_ram_size()
auto eagine::msgbus::remote_host::free_ram_size () const -> valid_if_positive< span_size_t > noexcept
Returns the free RAM size on the remote host.
See also
total_ram_size
free_swap_size
ram_usage
system_info::free_ram_size
Referenced by ram_usage().
free_swap_size()
auto eagine::msgbus::remote_host::free_swap_size () const -> valid_if_nonnegative< span_size_t > noexcept
Returns the free swap size on the remote host.
See also
total_swap_size
free_ram_size
swap_usage
system_info::total_ram_size
Referenced by swap_usage().
long_average_load()
auto eagine::msgbus::remote_host::long_average_load () const -> valid_if_nonnegative< float > noexcept
Returns the long average load on the remote host.
See also
short_average_load
system_info::long_average_load
ram_usage()
auto eagine::msgbus::remote_host::ram_usage () const -> valid_if_nonnegative<float> inline noexcept
Returns the RAM usage on the remote host (0.0, 1.0).
See also
total_ram_size
free_ram_size
short_average_load()
auto eagine::msgbus::remote_host::short_average_load () const -> valid_if_nonnegative< float > noexcept
Returns the short average load on the remote host.
See also
long_average_load
system_info::short_average_load
swap_usage()
auto eagine::msgbus::remote_host::swap_usage () const -> valid_if_nonnegative<float> inline noexcept
Returns the swap usage on the remote host (0.0, 1.0).
See also
total_swap_size
free_swap_size
total_ram_size()
auto eagine::msgbus::remote_host::total_ram_size () const -> valid_if_positive< span_size_t > noexcept
Returns the total RAM size on the remote host.
See also
free_ram_size
total_swap_size
ram_usage
system_info::total_ram_size
Referenced by ram_usage().
total_swap_size()
auto eagine::msgbus::remote_host::total_swap_size () const -> valid_if_positive< span_size_t > noexcept
Returns the total swap size on the remote host.
See also
free_swap_size
total_ram_size
swap_usage
system_info::total_swap_size
Referenced by swap_usage().
The documentation for this class was generated from the following file:
eagine/message_bus/remote_node.hpp
Copyright © 2015-2021 Matúš Chochlík.
<chochlik -at -gmail.com>
Documentation generated on Tue Apr 13 2021 by Doxygen (version 1.8.17).