Unit system
OGLplus (0.59.0) a C++ wrapper for rendering APIs
Unit system
Classes
class eagine::tagged_quantity< T, U >
Value of type T with a specified unit or tag type U.
Typedefs
template<typename T >
using eagine::seconds_t = tagged_quantity< T, units::second >
Alias for type storing duration values in seconds.
template<typename T >
using eagine::radians_t = tagged_quantity< T, units::radian >
Alias for type storing angle values in radians.
template<typename T >
using eagine::degrees_t = tagged_quantity< T, units::degree >
Alias for type storing angle values in degrees.
template<typename T >
using eagine::kelvins_t = tagged_quantity< T, units::kelvin >
Alias for type storing temperature values in kelvins.
Functions
template<typename T >
static constexpr auto eagine::seconds_ (T value) noexcept -> seconds_t< T >
Creates a tagged quantity storing value in seconds.
template<typename T >
static constexpr auto eagine::radians_ (T value) noexcept -> radians_t< T >
Creates a tagged quantity storing value in radians.
template<typename T >
static constexpr auto eagine::right_angles_ (T value) noexcept
Creates a tagged quantity in units of right angle.
static constexpr auto eagine::right_angle_ () noexcept
Creates a tagged quantity a right angle value.
template<typename T >
static constexpr auto eagine::turns_ (T value) noexcept
Creates a tagged quantity in full turn units.
template<typename T >
static constexpr auto eagine::degrees_ (T value) noexcept -> degrees_t< T >
Creates a tagged quantity storing value in degrees.
template<typename T >
static constexpr auto eagine::kelvins_ (T value) noexcept -> kelvins_t< T >
Creates a tagged quantity storing value in kelvins.
template<typename Qty , typename = std::enable_if_t<is_convertible_quantity_v<Qty, units::radian>>>
static constexpr auto sin (const Qty &qty)
Overload of sine for quantities of angle.
template<typename Qty , typename = std::enable_if_t<is_convertible_quantity_v<Qty, units::radian>>>
static constexpr auto cos (const Qty &qty)
Overload of cosine for quantities of angle.
template<typename Qty , typename = std::enable_if_t<is_convertible_quantity_v<Qty, units::radian>>>
static constexpr auto tan (const Qty &qty)
Overload of tangens for quantities of angle.
template<typename T >
static constexpr auto arcsin (T x)
Overload of arc sine for quantities of angle.
template<typename T >
static constexpr auto arccos (T x)
Overload of arc cosine for quantities of angle.
template<typename T >
static constexpr auto arctan (T y, T x)
Overload of tangens for quantities of angle.
template<typename T1 , typename U1 , typename T2 , typename U2 >
constexpr auto operator== (const tagged_quantity< T1, U1 > &a, const tagged_quantity< T2, U2 > &b) -> std::enable_if_t< units::is_convertible_v< U2, U1 >, bool >
Equality comparison.
template<typename T1 , typename U1 , typename T2 , typename U2 >
constexpr auto operator!= (const tagged_quantity< T1, U1 > &a, const tagged_quantity< T2, U2 > &b) -> std::enable_if_t< units::is_convertible_v< U2, U1 >, bool >
Nonequality comparison.
template<typename T1 , typename U1 , typename T2 , typename U2 >
constexpr auto operator< (const tagged_quantity< T1, U1 > &a, const tagged_quantity< T2, U2 > &b) -> std::enable_if_t< units::is_convertible_v< U2, U1 >, bool >
Less-than comparison.
template<typename T1 , typename U1 , typename T2 , typename U2 >
constexpr auto operator<= (const tagged_quantity< T1, U1 > &a, const tagged_quantity< T2, U2 > &b) -> std::enable_if_t< units::is_convertible_v< U2, U1 >, bool >
Less-equal comparison.
template<typename T1 , typename U1 , typename T2 , typename U2 >
constexpr auto operator> (const tagged_quantity< T1, U1 > &a, const tagged_quantity< T2, U2 > &b) -> std::enable_if_t< units::is_convertible_v< U2, U1 >, bool >
Greater-than comparison.
template<typename T1 , typename U1 , typename T2 , typename U2 >
constexpr auto operator>= (const tagged_quantity< T1, U1 > &a, const tagged_quantity< T2, U2 > &b) -> std::enable_if_t< units::is_convertible_v< U2, U1 >, bool >
Greater-equal comparison.
template<typename T , typename U >
constexpr auto operator+ (const tagged_quantity< T, U > &a)
Unary plus operator.
template<typename T , typename U >
constexpr auto operator- (const tagged_quantity< T, U > &a)
Unary negation operator.
template<typename T1 , typename U1 , typename T2 , typename U2 >
constexpr auto operator+ (const tagged_quantity< T1, U1 > &a, const tagged_quantity< T2, U2 > &b)
Addition operator.
template<typename T1 , typename U1 , typename T2 , typename U2 >
constexpr auto operator- (const tagged_quantity< T1, U1 > &a, const tagged_quantity< T2, U2 > &b)
Subtraction operator.
template<typename T1 , typename U1 , typename T2 , typename U2 >
constexpr auto operator* (const tagged_quantity< T1, U1 > &a, const tagged_quantity< T2, U2 > &b)
Multiplication operator.
template<typename T1 , typename U , typename T2 , typename = std::enable_if_t<!units::is_unit_v<T2> && !is_tagged_quantity_v<T2>>>
constexpr auto operator* (const tagged_quantity< T1, U > &a, const T2 &c)
Multiplication by constant operator.
template<typename T1 , typename T2 , typename U >
constexpr auto operator* (const T1 &c, const tagged_quantity< T2, U > &a)
Multiplication by constant operator.
template<typename T1 , typename U1 , typename U2 , typename = std::enable_if_t<units::is_unit_v<U2>>>
constexpr auto operator* (const tagged_quantity< T1, U1 > &a, U2)
Multiplication by unit operator.
template<typename T1 , typename U1 , typename T2 , typename U2 >
constexpr auto operator/ (const tagged_quantity< T1, U1 > &a, const tagged_quantity< T2, U2 > &b)
Division operator.
template<typename T1 , typename U , typename T2 , typename = std::enable_if_t<!units::is_unit_v<T2>>>
constexpr auto operator/ (const tagged_quantity< T1, U > &a, const T2 &c)
Division by constant operator.
template<typename T1 , typename U1 , typename U2 , typename = std::enable_if_t<units::is_unit_v<U2>>>
constexpr auto operator/ (const tagged_quantity< T1, U1 > &a, U2)
Constant division operator.
Detailed Description
Typedef Documentation
degrees_t
template<typename T > using eagine::degrees_t = typedef tagged_quantity<T, units::degree>
Alias for type storing angle values in degrees.
See also
degrees_
kelvins_t
template<typename T > using eagine::kelvins_t = typedef tagged_quantity<T, units::kelvin>
Alias for type storing temperature values in kelvins.
See also
kelvins_
radians_t
template<typename T > using eagine::radians_t = typedef tagged_quantity<T, units::radian>
Alias for type storing angle values in radians.
See also
radians_
seconds_t
template<typename T > using eagine::seconds_t = typedef tagged_quantity<T, units::second>
Alias for type storing duration values in seconds.
See also
seconds_
Function Documentation
arccos()
template<typename T > static constexpr auto arccos (T x) related
Overload of arc cosine for quantities of angle.
See also
radians_
degrees_
right_angles_
turns_
arcsin()
template<typename T > static constexpr auto arcsin (T x) related
Overload of arc sine for quantities of angle.
See also
radians_
degrees_
right_angles_
turns_
arctan()
template<typename T > static constexpr auto arctan (T y, T x) related
Overload of tangens for quantities of angle.
See also
radians_
degrees_
right_angles_
turns_
cos()
template<typename Qty , typename = std::enable_if_t<is_convertible_quantity_v<Qty, units::radian>>> static constexpr auto cos (const Qty & qty) related
Overload of cosine for quantities of angle.
See also
radians_
degrees_
right_angles_
turns_
degrees_()
template<typename T > static constexpr auto eagine::degrees_ (T value) -> degrees_t<T> static constexpr noexcept
Creates a tagged quantity storing value in degrees.
See also
radians_
right_angles_
right_angle_
turns_
Examples
application/002_spectrum/main.cpp, application/003_checker/main.cpp, application/020_bezier_patch/main.cpp, application/023_sketch/main.cpp, application/031_tessellation/main.cpp, application/032_translucent_arrow/main.cpp, application/040_metaballs/main.cpp, oglplus/002_glfw3_glew_triangle_compat.cpp, oglplus/003_glfw3_glew_checker_compat.cpp, oglplus/003_glfw3_glew_path_nv.cpp, oglplus/004_glfw3_glew_spiral_compat.cpp, and oglplus/009_glfw3_glew_cube_compat.cpp.
radians_()
template<typename T > static constexpr auto eagine::radians_ (T value) -> radians_t<T> static constexpr noexcept
Creates a tagged quantity storing value in radians.
See also
degrees_
right_angles_
right_angle_
turns_
Examples
application/025_recursive_cube/resources.cpp, application/032_translucent_arrow/resources.cpp, oglplus/012_glfw3_glew_cube.cpp, and oglplus/020_glfw3_glew_recursive_cube.cpp.
Referenced by eagine::right_angles_(), and eagine::turns_().
right_angle_()
static constexpr auto eagine::right_angle_ () static constexpr noexcept
Creates a tagged quantity a right angle value.
See also
radians_
degrees_
right_angles_
turns_
Examples
application/000_stencil_shadow/main.cpp, application/007_cube/main.cpp, application/008_yaml_shape/main.cpp, application/009_json_shape/main.cpp, application/016_torus/main.cpp, application/017_occlusion/main.cpp, application/018_uv_map/main.cpp, application/019_scaled_cubes/main.cpp, application/021_cel_shading/main.cpp, application/022_single_pass_edges/main.cpp, application/024_overdraw/main.cpp, application/026_halo/main.cpp, and application/028_compute_particles/main.cpp.
right_angles_()
template<typename T > static constexpr auto eagine::right_angles_ (T value) static constexpr noexcept
Creates a tagged quantity in units of right angle.
See also
radians_
degrees_
right_angle_
turns_
Examples
application/000_stencil_shadow/resources.cpp, application/019_scaled_cubes/resources.cpp, application/023_sketch/resources.cpp, and application/026_halo/resources.cpp.
Referenced by eagine::right_angle_().
sin()
template<typename Qty , typename = std::enable_if_t<is_convertible_quantity_v<Qty, units::radian>>> static constexpr auto sin (const Qty & qty) related
Overload of sine for quantities of angle.
See also
radians_
degrees_
right_angles_
turns_
tan()
template<typename Qty , typename = std::enable_if_t<is_convertible_quantity_v<Qty, units::radian>>> static constexpr auto tan (const Qty & qty) related
Overload of tangens for quantities of angle.
See also
radians_
degrees_
right_angles_
turns_
turns_()
template<typename T > static constexpr auto eagine::turns_ (T value) static constexpr noexcept
Creates a tagged quantity in full turn units.
See also
radians_
degrees_
right_angle_
right_angles_
Examples
application/019_scaled_cubes/resources.cpp, and application/021_cel_shading/resources.cpp.
Copyright © 2015-2021 Mat Chochlk.
<chochlik -at -gmail.com>
Documentation generated on Tue Apr 13 2021 by Doxygen (version 1.8.17).