# Copyright Matus Chochlik.
# Distributed under the Boost Software License, Version 1.0.
# See accompanying file LICENSE_1_0.txt or copy at
#  http://www.boost.org/LICENSE_1_0.txt
LIB_PREFIX = ALC
LIBRARY = oalplus
LIB_SUFFIX = _alc
SOURCES = $(wildcard *.txt)
PARENT = ..

sinclude ../common.mk
